version: "2.2"
services:
  echo:
    image: ghcr.io/supersonictw/popsenzawa-echo:main
    container_name: popsenzawa-echo
    depends_on:
      - redis
      - mariadb
    networks:
      - popsenzawa
    volumes:
      - ./config.toml:/workplace/config.toml:ro
      - ./country.mmdb:/workplace/country.mmdb:ro
    ports:
      - 127.0.0.1:8000:8000
    restart: always

  redis:
    image: redis:7-alpine
    container_name: popsenzawa-redis
    networks:
      - popsenzawa
    restart: always

  mariadb:
    image: mariadb:lts
    container_name: popsenzawa-mariadb
    networks:
      - popsenzawa
    volumes:
      - database:/var/lib/mysql:rw
      - ./initialize_db.sh:/initialize.sh:ro
    environment:
      MARIADB_USER: "popsenzawa_echo"
      MARIADB_PASSWORD: "popsenzawa_echo"
      MARIADB_DATABASE: "popsenzawa_echo"
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    restart: always

volumes:
  database:
    driver: local

networks:
  popsenzawa:
    driver: bridge
